// <auto-generated />
using Areyes.BaseDedatos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AReyes.Migrations
{
    [DbContext(typeof(AbarrotesReyesContext))]
    [Migration("20251122004044_nuevatabla")]
    partial class nuevatabla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AReyes.Models.ClienteEntity", b =>
                {
                    b.Property<string>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar")
                        .HasDefaultValueSql("generar_clave_Cliente()");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("varchar(70)");

                    b.HasKey("ClienteId")
                        .HasName("PK_ClienteId");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("AReyes.Models.EmpleadoEntity", b =>
                {
                    b.Property<string>("EmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar")
                        .HasDefaultValueSql("generar_clave_Empleado()");

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasColumnType("varchar(70)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasColumnType("varchar(70)");

                    b.Property<string>("Curp")
                        .IsRequired()
                        .HasColumnType("varchar(18)");

                    b.Property<string>("NombreEmpleado")
                        .IsRequired()
                        .HasColumnType("varchar(70)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.HasKey("EmpleadoId")
                        .HasName("PK_EmpleadoId");

                    b.ToTable("Empleados", (string)null);
                });

            modelBuilder.Entity("AReyes.Models.ProductoEntity", b =>
                {
                    b.Property<string>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar")
                        .HasDefaultValueSql("generar_clave_producto()");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("varchar(300)");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("ProductoId")
                        .HasName("PK_productoId");

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("AReyes.Models.ProveedorEntity", b =>
                {
                    b.Property<string>("ProveedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar")
                        .HasDefaultValueSql("generar_clave_Proveedor()");

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasColumnType("varchar(70)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasColumnType("varchar(70)");

                    b.Property<string>("NombreProveedor")
                        .IsRequired()
                        .HasColumnType("varchar(70)");

                    b.Property<string>("Rfc")
                        .IsRequired()
                        .HasColumnType("varchar(13)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.HasKey("ProveedorId")
                        .HasName("PK_ProveedorId");

                    b.ToTable("Proveedores", (string)null);
                });

            modelBuilder.Entity("AReyes.Models.UsuarioEntity", b =>
                {
                    b.Property<string>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar")
                        .HasDefaultValueSql("generar_clave_Usuario()");

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasColumnType("varchar(70)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasColumnType("varchar(70)");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("varchar(70)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.HasKey("UsuarioId")
                        .HasName("PK_UsuarioId");

                    b.ToTable("Usuarios", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
